
[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { suffix = ".hpp.in" }, { suffix = ".h.in" }]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "    " }
